# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-DebugShell-Jabber
version:      0.04
version_from: lib/POE/Component/DebugShell/Jabber.pm
installdirs:  site
requires:
    POE:                           0.2601
    POE::API::Peek:                0.02
    POE::Component::Jabber:        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
